### PR TITLE
Add bintray upload plugin

### PR DESCRIPTION
**Pull request by ataulm**
You can create an account on bintray.com, then you can use this plugin!

`./gradlew clean build bintrayUpload -Puser=romainpiel -PbintrayKey=YOUR_API_KEY -PdryRun=false`

That'll upload it to your private repo, but there's a button you can use to ask them to stick it on JCenter for you. That takes around a day, but after it's setup, you can use the command above and it'll push to your private repo and JCenter too.

### CODE REVIEW

**Comment by ataulm** [comment]
branch'll stay alive if you want to take a look

**Comment by romainpiel** [comment]
Why did you close it? It looks pretty mergeable to me!

**Comment by ataulm** [comment]
I didn't test it lol! wasn't sure if you wanted to give it a try yourself and make sure all was good.

**Comment by blundell** [comment]
bump 😈

**Comment by romainpiel** [comment]
Working on it! :)

**Comment by romainpiel** [comment]
Works like a charm with:

```
./gradlew clean build bintrayUpload -PbintrayUser=romainpiel -PbintrayKey=YOUR_API_KEY -PdryRun=false
```

https://bintray.com/romainpiel/maven/SVG2Android

Thanks a lot guys!

**Comment by ataulm** [comment]
Next step is requesting to add it to JCenter :grin:

**Comment by romainpiel** [comment]
I've requested to add it but I'm not sure how long it should take before it gets there. Should it move to JCenter straight after?

**Comment by blundell** [comment]
first time can take a bit of time. After the first time for a single repo, next time is basically instant

**Pull request merged**
